:sparkles: Button 스타일을 anchor tag에도 적용할수있도록 변경
rubric-dev/parte pull request #108
Opened 2023-06-26 05:25 UTC by june6723

## 개요
ERP, Iceberg 두 군데 모두 button형태의 a tag가 많이 보여 각 프로젝트에서 LinkButton을 쉽게 만들 수 있도록 지원 해봤습니다.

- `buttonStyles` css 객체를 만들어서 `Button`도 `buttonStyles`를 사용해서 스타일링함
이렇게 하면 각 프로젝트에서 (리액트건 Next건) LinkButton을 만들기가 쉬워짐
아래가 예시 코드입니다

```tsx
const CustomLinkStyle = styled.a<ButtonStylingProps>`
  ${buttonStyles}
`;

const CustomLink = ({
  children,
  variant = "fill-primary",
  direction = "horizontal",
  leadingIcon,
  trailingIcon,
  ...props
}: PropsWithChildren<
  ButtonStylingProps & AnchorHTMLAttributes<HTMLAnchorElement>
>) => {
  return (
    <CustomLinkStyle variant={variant} direction={direction} {...props}>
      {leadingIcon &&
        cloneElement(leadingIcon as ReactElement, {
          size: direction === "horizontal" ? 12 : 16,
        })}
      {children}
      {trailingIcon &&
        cloneElement(trailingIcon as ReactElement, {
          size: direction === "horizontal" ? 12 : 16,
        })}
    </CustomLinkStyle>
  );
};

```

저렇게 styled.a 라고 선언하면 a태그로 만들어지고 바닐라 react 라면 react-router-dom 에서 제공해주는 Link를, Nextjs라면 넥스트가 지원하는 Link 컴포넌트로 쉽게 생성이 가능합니다.

다만 leadingIcon, trailingIcon 같은 경우는 `children`과 비슷하게 직접 써줘야 하더라구요.
그래도 이렇게하면 스타일링은 공통으로 가져갈 수 있어서 괜찮다고 생각합니다

2023-06-27 00:56 UTC, dohye1 requested changes

2023-06-27 00:56 UTC, dohye1 commented on packages/parte-ui/src/Button/LinkButton.tsx
> +};
음....그냥 basebutton을 하나만들어서 스타일 관리하는역할을 담당하게하고, 
basebutton을 확장한 Button, LinkButton을 만드는건 어때요??

2023-06-27 00:56 UTC, dohye1 commented on packages/parte-ui/src/Button/index.ts
> +export { buttonStyles } from "./Button.styled";
buttonStyles를 export해야하는 이유가 무엇이지요??

2023-06-30 07:02 UTC, june6723 commented on packages/parte-ui/src/Button/LinkButton.tsx
> +};
baseButton을 어떻게 만들어야힐지 모르겠네요... ㅜ
일단 스타일은 공통으로 묶었는데 혜안을 주십쇼...

2023-07-03 09:21 UTC, dohye1 approved these changes
댓글남긴거 수정해주시고 머지하셔도될듯!

2023-07-03 09:21 UTC, dohye1 commented on packages/parte-ui/src/Button/index.ts
> +  type ButtonStylingProps,
이것도 export 할 필요 없을것같아요

2023-07-04 01:01 UTC, merged