:lipstick: 버튼 디자인 수정
rubric-dev/parte pull request #203
Opened 2024-02-16 10:00 UTC by Wish-baek

2024-02-17 00:39 UTC, dohye1 approved these changes

2024-02-17 00:40 UTC, dohye1 requested changes
리뷰해야함

2024-02-19 04:27 UTC, dohye1 commented on packages/parte-ui/src/Button/Button.styled.ts
> +      : `${theme.spacing.spacing48}px`};
폰트사이즈는 2개로 분기, 높이는 3개로 분기가 맞나요?
가독성고려해서 ts-pattern써도될듯?!
아니면 다른 디자인시스템에서 3개이상의 분기가 발생햇을때 스타일 어떻게 적용하는지 함 참고해봐요ㅕ!

2024-02-19 04:30 UTC, june6723 requested changes

2024-02-19 04:30 UTC, june6723 commented on packages/parte-ui/src/Button/Button.types.ts
> +  size?: "medium" | "large" | "x-large";
type으로 따로 지정해서 export 할것

2024-02-19 04:30 UTC, june6723 commented on packages/parte-ui/src/Button/Button.styled.ts
> +      : `${theme.spacing.spacing14}`};
spacing은 폰트 크기에 쓰려고 만든 토큰이 아닐거라서 창희님이랑 이야기 해보시고 적절하게 바꾸세요

2024-02-19 04:30 UTC, june6723 commented on packages/parte-ui/src/Button/Button.styled.ts
> +      : `${theme.spacing.spacing48}px`};
삼항 연산자 중첩 쓰지 마시고 switch문 같은걸로 변경해주세요

2024-02-19 04:30 UTC, june6723 commented on packages/parte-ui/src/Button/Button.styled.ts
> +      : `${theme.spacing.spacing14}`};
아마 typography로 써야할수도 있음

2024-02-20 01:45 UTC, dohye1 approved these changes
소원님 머지하시죠

2024-02-20 01:52 UTC, june6723 approved these changes

2024-02-20 01:52 UTC, merged